// Builds installers from a packaged app in release/ (run "npm run package:win" or "package:linux" first).
//
//   node scripts/installer.mjs --platform win32    NSIS setup program  (needs makensis: apt install nsis / choco install nsis)
//   node scripts/installer.mjs --platform linux    Debian package      (needs dpkg-deb)
//
// Windows: a per-user install into %LOCALAPPDATA%\Programs\Undertone. No administrator rights, Start
// menu and optional desktop shortcuts, an entry under "Installed apps" and an uninstaller. Supports
// silent install and uninstall with /S. The setup program is not code-signed.
// Linux: installs to /opt/Undertone with a launcher entry, an icon and an "undertone" command.
// Neither installer touches your conversations or settings; uninstalling leaves them in place.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const platform = arg('platform', process.platform);
const arch = arg('arch', 'x64');
const product = pkg.productName;
const version = pkg.version;
const releaseDir = path.join(root, 'release');
const appDir = path.join(releaseDir, `${product}-${platform}-${arch}`);
const homepage = 'https://github.com/kirtanbhatt10/undertone-desktop';

if (!['win32', 'linux'].includes(platform)) {
  console.error(`No installer is defined for "${platform}" (supported: win32, linux).`);
  process.exit(1);
}
if (!fs.existsSync(appDir)) {
  console.error(`No packaged app at ${path.relative(root, appDir)}. Run "npm run package${platform === 'win32' ? ':win' : ':linux'}" first.`);
  process.exit(1);
}

function folderSizeKb(dir) {
  let bytes = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) bytes += folderSizeKb(full) * 1024;
    else if (entry.isFile()) bytes += fs.statSync(full).size;
  }
  return Math.ceil(bytes / 1024);
}

function report(file) {
  const mb = (fs.statSync(file).size / 1024 / 1024).toFixed(1);
  console.log(`Built ${path.relative(root, file)} (${mb} MB)`);
}

// ---------------------------------------------------------------------------------------------
// Windows: NSIS
// ---------------------------------------------------------------------------------------------

function buildWindows() {
  const exe = `${product}.exe`;
  if (!fs.existsSync(path.join(appDir, exe))) throw new Error(`${exe} is missing from ${path.relative(root, appDir)}.`);
  const outFile = path.join(releaseDir, `${product}-Setup-${version}-${arch}.exe`);
  // installer.ico holds plain-bitmap images (16 to 64 px), which every NSIS version accepts.
  const icon = path.join(root, 'resources', 'installer.ico');
  const uninstallKey = `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${product}`;
  // makensis accepts forward slashes in compile-time paths on every host OS.
  const posix = (p) => p.split(path.sep).join('/');

  const nsi = `; Generated by scripts/installer.mjs. Do not edit by hand.
Unicode true
SetCompressor /SOLID lzma
RequestExecutionLevel user

!include "MUI2.nsh"

!define PRODUCT "${product}"
!define VERSION "${version}"
!define EXE "${exe}"
!define UNINSTALL_KEY "${uninstallKey}"

Name "\${PRODUCT}"
OutFile "${posix(outFile)}"
InstallDir "$LOCALAPPDATA\\Programs\\\${PRODUCT}"
InstallDirRegKey HKCU "Software\\\${PRODUCT}" "InstallDir"
ShowInstDetails nevershow
ShowUninstDetails nevershow
BrandingText "\${PRODUCT} \${VERSION}"

VIProductVersion "${version}.0"
VIAddVersionKey "ProductName" "\${PRODUCT}"
VIAddVersionKey "ProductVersion" "\${VERSION}"
VIAddVersionKey "FileVersion" "\${VERSION}"
VIAddVersionKey "FileDescription" "\${PRODUCT} Setup"
VIAddVersionKey "LegalCopyright" "MIT licence"

!define MUI_ICON "${posix(icon)}"
!define MUI_UNICON "${posix(icon)}"
!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_RUN "$INSTDIR\\\${EXE}"
!define MUI_FINISHPAGE_RUN_TEXT "Start \${PRODUCT}"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${posix(path.join(root, 'LICENSE'))}"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "\${PRODUCT}" SecApp
  SectionIn RO
  SetShellVarContext current
  SetOutPath "$INSTDIR"
  File /r "${posix(appDir)}/*"
  File "/oname=icon.ico" "${posix(icon)}"
  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  CreateShortcut "$SMPROGRAMS\\\${PRODUCT}.lnk" "$INSTDIR\\\${EXE}" "" "$INSTDIR\\icon.ico"

  WriteRegStr HKCU "Software\\\${PRODUCT}" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "DisplayName" "\${PRODUCT}"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "DisplayVersion" "\${VERSION}"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "Publisher" "Undertone contributors"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "URLInfoAbout" "${homepage}"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\\icon.ico"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'
  WriteRegStr HKCU "\${UNINSTALL_KEY}" "QuietUninstallString" '"$INSTDIR\\Uninstall.exe" /S'
  WriteRegDWORD HKCU "\${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "\${UNINSTALL_KEY}" "NoRepair" 1
  WriteRegDWORD HKCU "\${UNINSTALL_KEY}" "EstimatedSize" ${folderSizeKb(appDir)}
SectionEnd

Section "Desktop shortcut" SecDesktop
  SetShellVarContext current
  CreateShortcut "$DESKTOP\\\${PRODUCT}.lnk" "$INSTDIR\\\${EXE}" "" "$INSTDIR\\icon.ico"
SectionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT \${SecApp} "The \${PRODUCT} application."
  !insertmacro MUI_DESCRIPTION_TEXT \${SecDesktop} "Add a shortcut to the desktop."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

Section "Uninstall"
  SetShellVarContext current
  Delete "$SMPROGRAMS\\\${PRODUCT}.lnk"
  Delete "$DESKTOP\\\${PRODUCT}.lnk"
  ; Only the program folder is removed. Conversations, settings and saved keys in
  ; %APPDATA%\\\${PRODUCT} are left alone; delete that folder by hand for a clean slate.
  RMDir /r "$INSTDIR"
  DeleteRegKey HKCU "\${UNINSTALL_KEY}"
  DeleteRegKey HKCU "Software\\\${PRODUCT}"
SectionEnd
`;
  const script = path.join(releaseDir, 'installer.nsi');
  fs.writeFileSync(script, nsi);
  fs.rmSync(outFile, { force: true });
  execFileSync('makensis', ['-V2', '-INPUTCHARSET', 'UTF8', script], { stdio: 'inherit' });
  report(outFile);
}

// ---------------------------------------------------------------------------------------------
// Linux: .deb
// ---------------------------------------------------------------------------------------------

function buildDebian() {
  const bin = product.toLowerCase();
  if (!fs.existsSync(path.join(appDir, bin))) throw new Error(`${bin} is missing from ${path.relative(root, appDir)}.`);
  const debArch = arch === 'x64' ? 'amd64' : arch;
  const stage = path.join(releaseDir, 'deb');
  const outFile = path.join(releaseDir, `${pkg.name}_${version}_${debArch}.deb`);
  fs.rmSync(stage, { recursive: true, force: true });

  const opt = path.join(stage, 'opt', product);
  fs.mkdirSync(path.dirname(opt), { recursive: true });
  fs.cpSync(appDir, opt, { recursive: true, verbatimSymlinks: true });

  fs.mkdirSync(path.join(stage, 'usr', 'bin'), { recursive: true });
  fs.symlinkSync(`/opt/${product}/${bin}`, path.join(stage, 'usr', 'bin', bin));

  const icons = path.join(stage, 'usr', 'share', 'icons', 'hicolor', '512x512', 'apps');
  fs.mkdirSync(icons, { recursive: true });
  fs.copyFileSync(path.join(root, 'resources', 'icon.png'), path.join(icons, `${bin}.png`));

  const apps = path.join(stage, 'usr', 'share', 'applications');
  fs.mkdirSync(apps, { recursive: true });
  fs.writeFileSync(
    path.join(apps, `${bin}.desktop`),
    ['[Desktop Entry]', 'Type=Application', `Name=${product}`, `Comment=${pkg.description}`, `Exec=/opt/${product}/${bin} %U`, `Icon=${bin}`, 'Terminal=false', 'Categories=Office;Utility;', `StartupWMClass=${product}`, ''].join('\n'),
  );

  const debian = path.join(stage, 'DEBIAN');
  fs.mkdirSync(debian, { recursive: true });
  fs.writeFileSync(
    path.join(debian, 'control'),
    [
      `Package: ${pkg.name}`,
      `Version: ${version}`,
      'Section: utils',
      'Priority: optional',
      `Architecture: ${debArch}`,
      `Installed-Size: ${folderSizeKb(opt)}`,
      // The t64 names are the same libraries on Ubuntu 24.04 and Debian 13.
      'Depends: libgtk-3-0t64 | libgtk-3-0, libasound2t64 | libasound2, libnss3, libgbm1, libxss1, libxtst6, libnotify4, xdg-utils',
      'Recommends: libsecret-1-0, gnome-keyring',
      'Maintainer: Undertone contributors <noreply@github.com>',
      `Homepage: ${homepage}`,
      `Description: ${pkg.description}`,
      ' Context-aware chat, meeting mode and screen capture in a small floating window.',
      ' Works with Anthropic, OpenAI and OpenAI-compatible servers, or offline in Mock mode.',
      '',
    ].join('\n'),
  );
  // Chromium's sandbox helper must be setuid root on kernels without unprivileged user namespaces.
  fs.writeFileSync(path.join(debian, 'postinst'), `#!/bin/sh\nset -e\nchmod 4755 "/opt/${product}/chrome-sandbox" || true\n`, { mode: 0o755 });

  fs.rmSync(outFile, { force: true });
  execFileSync('dpkg-deb', ['--build', '--root-owner-group', '-Zxz', stage, outFile], { stdio: 'inherit' });
  fs.rmSync(stage, { recursive: true, force: true });
  report(outFile);
}

if (platform === 'win32') buildWindows();
else buildDebian();
